// swift-tools-version: 5.10
// This file is GENERATED by kitchenos-client-sdk/scripts/ci/publish_xcframework_public.sh
// from scripts/ci/templates/Package.swift.template. Do not edit it by hand — the version and
// checksum must always describe the same artifact, so they are written together or not at all.
import PackageDescription

let package = Package(
  name: "kitchenos-client-sdk-swift",
  platforms: [.iOS(.v15)],
  products: [
    .library(name: "KitchenOS", targets: ["KitchenOS"])
  ],
  targets: [
    .binaryTarget(
      name: "KitchenOS",
      url: "https://github.com/dropkitchen/kitchenos-client-sdk-swift/releases/download/v1.61.0/KitchenOS.xcframework.zip",
      checksum: "3754590560f3b7a5dafd2070e40157c651633fca0624221f105f2d3735841c64"
    )
  ]
)
