// swift-tools-version: 5.10
// This file is GENERATED by kitchenos-client-sdk/scripts/ci/publish_xcframework_public.sh
// from scripts/ci/templates/Package.swift.template. Do not edit it by hand — the version and
// checksum must always describe the same artifact, so they are written together or not at all.
import PackageDescription

let package = Package(
  name: "kitchenos-client-sdk-swift",
  platforms: [.iOS(.v15)],
  products: [
    .library(name: "KitchenOS", targets: ["KitchenOS"])
  ],
  targets: [
    .binaryTarget(
      name: "KitchenOS",
      url: "https://github.com/dropkitchen/kitchenos-client-sdk-swift/releases/download/v1.68.0/KitchenOS.xcframework.zip",
      checksum: "9efd2876eb3f094959b16e112130d0447c9aa90ae0a280dd46b012c606b668d8"
    )
  ]
)
